// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKsxfD853Q-Ou__S0WSnEbyulbkKZvze4',
    appId: '1:683805837679:web:83cb0d7d71fe958acac09a',
    messagingSenderId: '683805837679',
    projectId: 'flutter-notifications-61706',
    authDomain: 'flutter-notifications-61706.firebaseapp.com',
    storageBucket: 'flutter-notifications-61706.appspot.com',
    measurementId: 'G-W16NHSZD0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9JheuGiw-NmS4lwnGK6DpuwjwTz3KiCs',
    appId: '1:683805837679:android:8ffe27e4b0805001cac09a',
    messagingSenderId: '683805837679',
    projectId: 'flutter-notifications-61706',
    storageBucket: 'flutter-notifications-61706.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHqs23rrnrE-zMHJngwG8rSglaPqsSCNk',
    appId: '1:683805837679:ios:b294961e88a2abd6cac09a',
    messagingSenderId: '683805837679',
    projectId: 'flutter-notifications-61706',
    storageBucket: 'flutter-notifications-61706.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHqs23rrnrE-zMHJngwG8rSglaPqsSCNk',
    appId: '1:683805837679:ios:b294961e88a2abd6cac09a',
    messagingSenderId: '683805837679',
    projectId: 'flutter-notifications-61706',
    storageBucket: 'flutter-notifications-61706.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseNotification',
  );
}
